# syntax=docker/dockerfile:1
FROM busybox
CMD echo "Hello world! This is my first Docker image."

# FROM pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel

# RUN apt update

# RUN pip install pytorch-lightning
